version: '3'
services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: goapp:compose
    container_name: goapp
    ports:
      - 8080:8080
    environment:
      DB_HOST: psql
      DB_USER: demo
      DB_PASSWORD: admin123
    depends_on:
      - psql
  psql:
    image: postgres:11
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./datastore:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: admin123
volumes:
  postgres-data: